'\" t
.TH "SYSTEM-SNAPSHOT" "8" "" "" "system-snapshot"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
system\-snapshot \- Create, merge or discard system snapshots 
.SH "SYNOPSIS"
.HP \w'\fBsystem\-snapshot\ \fR\fB[OPTIONS...]\fR\fB'u
\fBsystem\-snapshot \fR\fB[OPTIONS...]\fR\fB
.SH "DESCRIPTION"
.PP
\fBsystem\-snapshot\fR
may be used to create snapshots and backups of the boot directory before performing any change to the system\&. Any change may performed afterwards so the system can be rolled back to the previous state\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-create\fR
.RS 4
Creates the boot dir backup and the snapshots of the LVs specified in the config file\&.
.RE
.PP
\fB\-\-rollback\fR
.RS 4
Recovers the boot backup and merges the snapshots so the LVs come back to the previous state\&.
.RE
.PP
\fB\-\-rollback\-and\-reboot\fR
.RS 4
Performs a rollback and, if no error is detected, reboots the machine\&.
.RE
.PP
\fB\-\-discard\fR
.RS 4
Cleans up the boot backup and discards the snapshots\&. To be used when changes applied correctly\&.
.RE
.PP
\fB\-\-cleanup\fR
.RS 4
Cleans up the boot backup and snapshots with minimum checks\&. To be used when changes did not apply correctly\&. No check will be performed before cleaning up backups and snapshots\&.
.RE
.PP
\fB\-\-info\fR
.RS 4
Shows if snapshots and backup are available\&. If so, displays information about the snapshots and backup\&. 
.RE
.PP
.SH "EXIT VALUES"
.PP 
.IP "\fB0\fP"
Success
.IP "\fB1\fP"
No parameters received 
.IP "\fB2\fP"
Command not run as root
.IP "\fB3\fP"
Main config file not found
.IP "\fB4\fP"
No backup devices defined in config file 
.IP "\fB5\fP"
Snapshot already in place
.IP "\fB6\fP"
Error during snapshot creation
.IP "\fB7\fP"
Problem with backup config file
.IP "\fB8\fP"
LV device not found
.IP "\fB9\fP"
Error during rollback
.IP "\fB10\fP"
Error during discard
.IP "\fB11\fP"
Error during boot restore
.IP "\fB12\fP"
Another instance running
.IP "\fB13\fP"
Lockfile not found
.IP "\fB14\fP"
Not enough space in Volume Group
.IP "\fB15\fP"
Not enough space in Boot Backup dir
.RE
.SH "NOTES"
.PP
It is recommended to keep /var/log in a different LV and not including it in the list of volumes to snapshot.
.SH "FILES"
.PP
Variables are sourced from config file in /etc/sysconfig/system-snapshot\&.
.PP
Snapshot info is stored in file config in backup dir, by default /var/system-snapshot/config\&.
.SH "SEE ALSO"
.PP
\fBlvm\fR(8),
\fBlvcreate\fR(8),
